### PR TITLE
Update `prombench/benchmark` manifests

### PR DESCRIPTION
**Pull request by Vandit1604**
In this PR, I have 
- updated the version of grafana/promtail to `3.0.0`
- updated deprecated configurations of promtail

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
Seems plausible.

**Comment by bboreham** [comment]
Why do we have two configmaps for promtail that look very similar?

**Comment by bboreham** [comment]
Why is it running 3 promtails?  This seems unnecessary.

**Comment by Vandit1604** [comment]
This one is to get the logs from each node via tha daemonset https://github.com/prometheus/test-infra/blob/master/prombench/manifests/cluster-infra/6d_promtail_daemon_set.yaml#L34

This promtail has two deployments because for when testing PR and One for testing against a Release. Is there a way to have this deployment conditonally?

https://github.com/prometheus/test-infra/blob/master/prombench/manifests/prombench/benchmark/3c_promtail-bench_deployment.yaml#L169-L179

**Comment by bboreham** [comment]
The DaemonSet only runs on one node, due to https://github.com/prometheus/test-infra/blob/master/prombench/manifests/cluster-infra/6d_promtail_daemon_set.yaml#L124

It’s unnecessary to have all this complication; I’ll fix it.

**Comment by bboreham** [comment]
Cleanup is in #749.  Currently running that config [here](http://prombench.prometheus.io/grafana/explore?schemaVersion=1&panes=%7B%225f8%22:%7B%22datasource%22:%22PEEA25C9CAAE5E714%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PEEA25C9CAAE5E714%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bcontainer_name%21%3D%5C%22%5C%22%7D%20%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-5m%22,%22to%22:%22now%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22columns%22:%7B%220%22:%22Time%22,%221%22:%22Line%22,%222%22:%22container_name%22%7D,%22visualisationType%22:%22logs%22,%22labelFieldName%22:%22labels%22,%22refId%22:%22A%22%7D%7D%7D%7D&orgId=1)

BTW the newest promtail appears to be 3.2.0.

**Comment by Vandit1604** [comment]
> BTW the newest promtail appears to be 3.2.0.

I'll update it to the latest.

**Comment by Vandit1604** [comment]
Rebased the PR

**Comment by Vandit1604** [comment]
Solved the merge conflicts.
Is there anything that needs to be done for this to get merged?

gentle ping @bboreham

**Review by bwplotka — APPROVED** [review]
Thank you!

**Pull request merged**
