### PR TITLE
Moved all workloads log.format to JSON (where it's implemented).

### PR DESCRIPTION
**Pull request by bwplotka**
This solves problem with GKE logging to assume all lines as errors.

Also updating meta Prometheus to 3.0

Once this PR is approved, I will kube apply infra resources (testing on production!)

### CODE REVIEW

**Comment by bwplotka** [comment]
Hope it will not break the Loki though.

**Review by kakkoyun — APPROVED** [review]
LGTM

**Comment by kakkoyun** [comment]
@bboreham any objections to merging?

**Comment by bwplotka** [comment]
Applying to test today, before merging.

**Comment by bboreham** [comment]
I find JSON logs annoying; as a matter of courtesy I am not taking a strong position regarding products from my employer.

**Comment by bwplotka** [comment]
@bboreham flagged a good point that JSON will be a bit more painful to deal on raw files. I will keep looking if there's a way to configure GKE logging for this, otherwise we can leave with "errors" as all level in GKE logging UI, not a big struggle.

Closing for now, thanks!

**Pull request closed without merging**
