### PR TITLE
change order of deletion in resource_delete

### PR DESCRIPTION
**Pull request by geekodour**
Gets rid of the following error, this error is fatal now as prombench exits on error.
```
11:51:21 gke.go:576: error while deleting objects from a manifest file err:error deleting 'manifests/prombench/benchmark/1c_cluster-role-binding.yaml' err:resource delete failed - kind: Role, name: loadgen-scaler: roles.rbac.authorization.k8s.io "loadgen-scaler" not found
make: *** [Makefile:41: resource_delete] Error 1
```

Signed-off-by: Hrishikesh Barman <hrishikeshbman@gmail.com>

cc @krasi-georgiev

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
do you know why this happens?

**Comment by geekodour** [comment]
```
resource_delete:
	$(PROMBENCH_CMD) gke resource delete -a ${AUTH_FILE} \
		-v ZONE:${ZONE} -v PROJECT_ID:${PROJECT_ID} -v CLUSTER_NAME:${CLUSTER_NAME} -v PR_NUMBER:${PR_NUMBER} \
		-f manifests/prombench/benchmark/1a_namespace.yaml \
        -f manifests/prombench/benchmark/1c_cluster-role-binding.yaml
```
this target deletes the namespace first and also deletes the roles and rolebindings. but the clusterroles are not part  of the namespace so they need to be deleted separately.

since `loadgen-scaler` role and rolebindings were in `1c_cluster-role-binding.yaml` and were already deleted when deleting the namespace. hence this error

**Comment by krasi-georgiev** [comment]
I think these are executed in the sequence they are provided so maybe can combine  nodepool_delete and resource_delete and just have something like:

```
delete:
	$(PROMBENCH_CMD) gke resource delete -a ${AUTH_FILE} \
		-v ZONE:${ZONE} -v PROJECT_ID:${PROJECT_ID} -v CLUSTER_NAME:${CLUSTER_NAME} -v PR_NUMBER:${PR_NUMBER} \
        -f manifests/prombench/benchmark/1c_cluster-role-binding.yaml \
		-f manifests/prombench/benchmark/1a_namespace.yaml \				
		-f manifests/prombench/nodepools.yaml
```

this will delete the role bindings first, than the namespace and only than the nodepools, right?

**Comment by geekodour** [comment]
@krasi-georgiev tested by changing the order, working now. 
about,
```
-f manifests/prombench/nodepools.yaml
```
we are using a separate command `./prombench gke nodepool delete` so kept that  as is.

**Comment by krasi-georgiev** [comment]
sorry I didn't understand, why do we need `nodepool_delete` and `resource_delete`, why not just have one?

**Comment by geekodour** [comment]
@krasi-georgiev the prombench commands for each is different,

https://github.com/prometheus/prombench/blob/0498f012444b7b550e2780b8d0011ca3d93e8c01/prombench/Makefile#L47

vs

https://github.com/prometheus/prombench/blob/0498f012444b7b550e2780b8d0011ca3d93e8c01/prombench/Makefile#L41

**Comment by krasi-georgiev** [comment]
ooh yes, I completely forgot about that.

**Pull request merged**
