### PR TITLE
Updating the import path for containerpb (gke)

### PR DESCRIPTION
**Pull request by saketjajoo**
The older import path
(google.golang.org/genproto/googleapis/container/v1) has been deprecated
and got migrated to cloud.google.com/go/container/apiv1/containerpb.
Reference:
- https://pkg.go.dev/google.golang.org/genproto/googleapis/container/v1#pkg-overview
- Migration Guide: https://github.com/googleapis/google-cloud-go/blob/main/migration.md

### CODE REVIEW

**Comment by maxamins** [comment]
Please add a description describing why this change was necessary.

**Review by maxamins — APPROVED** [review]

**Review by maxamins — APPROVED** [review]
Good job!

**Comment by saketjajoo** [comment]
c.c: @bwplotka - Can you please review and approve this PR?

**Review by bwplotka — APPROVED** [review]
Thanks a lot!

**Pull request merged**
