### PR TITLE
Move all tools from /cmd/.. to /tools/...

### LINKED ISSUE #239: move all tools from /cmd/.. to /tools/...
Leave just the prombench tool in /cmd/prombench and move all the other cli in /tools

cc @nikita-mk

### PR DESCRIPTION
**Pull request by nikita-mk**
Closes #239 
All cli tools in `/cmd` are moved to `/tools`. Now, only the prombench cli tool is present in`/cmd`.

Signed-off-by: nikita-mk <nikkikokitkar@gmail.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
what about updating the promu build config?

Not sure why the circle tests hasn't started, but the build test fails.

Also this reminds me that need to add the `commentMonitor` build config to promu as well.

Can you find out why the test haven't started on this PR?

**Comment by nikita-mk** [comment]
Sure

**Comment by krasi-georgiev** [comment]
commentMonitor is missing form the promu config.

**Comment by nikita-mk** [comment]
Do we need to build commentMonitor? I have added command to build it in the dockerfile itself. https://github.com/prometheus/prombench/blob/master/cmd/tools/commentMonitor/Dockerfile

**Comment by krasi-georgiev** [comment]
Although the Dockerfile doesn't use it that config is used for the circle CI build test and we want to know that the binary builds successfully.

**Comment by krasi-georgiev** [comment]
ping @nikita-mk

**Pull request closed without merging**
