### PR TITLE
Replace the kubernetes.io/ingress.class into spec.ingressClassName.

### PR DESCRIPTION
**Pull request by kushalShukla-web**
kubernetes.io/ingress.class is deprecated .

### CODE REVIEW

**Comment by kushalShukla-web** [comment]
solves #720

**Comment by Vandit1604** [comment]
Hi @kushalShukla-web,
Can you update `kubernetes.io/ingress.class` at [these places](https://github.com/search?q=repo%3Aprometheus%2Ftest-infra%20kubernetes.io%2Fingress.class&type=code) as well?
Thanks for the PR.

**Comment by kushalShukla-web** [comment]
sure

**Review by bwplotka — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
