### PR TITLE
query from reverse-proxy URL of prometheus servers being benchmarked

### PR DESCRIPTION
**Pull request by sipian**
~~AFAIR We had removed these scraping targets earlier, assuming we didn't need them and to reduce unnecessary scraping.~~
~~Turns out we need them for prometheus-query metrics.~~

~~For prom-pr, the first target will be down & for prom-release, the 2nd target will be down.~~

~~[sample query graphs](http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&from=1544029828196&to=1544030136903&var-RuleGroup=All&var-pr-number=4576)~~
Signed-off-by: sipian <cs15btech11019@iith.ac.in>

### CODE REVIEW

**Comment by sipian** [comment]
There are gaps in these graphs because in the query

`rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"inner_eval\",namespace=\"prombench-[[pr-number]]\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"inner_eval\",namespace=\"prombench-[[pr-number]]\",prometheus=~\"(test+).*\"}[1m])`

sometimes the denominator becomes 0, making the result NaN.

Currently the graphs show, average time to serve 1 query.
If the gaps are a problem, I can change the query to find average time to server all queries.

**Comment by krasi-georgiev** [comment]
shouldn't the meta Prometheus instance scrape these directly?

**Comment by sipian** [comment]
[These](http://prombench.prometheus.io/prometheus-meta/graph?g0.range_input=1h&g0.expr=loadgen_queries_total%7Bnamespace%3D%22prombench-4962%22%7D&g0.tab=0&g1.range_input=1h&g1.expr=loadgen_failed_queries_total%7Bnamespace%3D%22prombench-4962%22%7D&g1.tab=0&g2.range_input=1h&g2.expr=loadgen_query_duration_seconds_count%7Bnamespace%3D%22prombench-4962%22%7D&g2.tab=0) are the metrics exposed by the querier.

[These](http://prombench.prometheus.io/4576/prometheus-pr/graph?g0.range_input=1h&g0.expr=prometheus_engine_query_duration_seconds_sum&g0.tab=0&g1.range_input=1h&g1.expr=prometheus_engine_query_duration_seconds_count&g1.tab=0&g2.range_input=1h&g2.expr=prometheus_engine_query_duration_seconds&g2.tab=0) are the query metrics scraped by a prom being benchmarked. Since the graphs are almost straight lines in the second link, rate([1m]) becomes 0 almost all the times, making the result NaN.

Maybe instead of fixed interval of sleeping, we can add some random intervals sleeping in the [querier](https://github.com/prometheus/prombench/blob/master/cmd/load-generator/main.py#L98).

And yeah you are right, meta is scraping the prom metrics, we don't need static_target of `localhost:9090`.

**Comment by sipian** [comment]
The querier logs seem to be showing 404, checking it.

**Comment by sipian** [comment]
Because of #165, the query URL for the prometheus servers being benchmarked changed to `web-external-url`.
I had forgotten to update the URL then.
Ready for review now.

**Comment by sipian** [comment]
Now query timings are being graphed properly.
http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&var-RuleGroup=All&var-pr-number=4964

**Comment by sipian** [comment]
@krasi-georgiev 
I think this is ready for a final review.
I have tested this script on a [deployment](http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&var-RuleGroup=All&var-pr-number=4964) too.

**Comment by krasi-georgiev** [comment]
I just had  another idea to simplify the querier
why not just hard fail after lets say 30  - 404 errors
or any other number that makes sense depending on how long it sleeps between requests.
this way we would need the hacky initcontainers and will still hard fail when there is a major problem.

**Review by krasi-georgiev — APPROVED** [review]

**Pull request merged**
