### PR TITLE
Replace port numbers by port names

### LINKED ISSUE #108: Use port names for all servicePort instead of numbers for all manifest files.

### PR DESCRIPTION
**Pull request by nikita-mk**
Fixes #108 
Signed-off-by: niki-1905 <nikkikokitkar@gmail.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
the idea here is to use port names for the manifest files. 

https://github.com/prometheus/prombench/search?q=servicePort&unscoped_q=servicePort

**Comment by nikita-mk** [comment]
I will make the necessary changes.

**Comment by krasi-georgiev** [comment]
ok, thanks, please make sure you test the changes by applying the manifest files.

**Comment by nikita-mk** [comment]
Do I need to create my own GKE cluster and run the tests?

**Comment by krasi-georgiev** [comment]
of course  :smile:

**Comment by nikita-mk** [comment]
I am not able to figure out the reference for the `servicePort` in `components/prombench/manifests/benchmark/5_nginx-ingress-routes.yaml`. No portname is defined for port 80 in other files.

**Comment by krasi-georgiev** [comment]
have a look at this PR I hope this helps.
https://github.com/prometheus/prombench/pull/106/files

**Comment by sipian** [comment]
Check the `Service` object yaml configuration in https://github.com/prometheus/prombench/blob/master/components/prombench/manifests/benchmark/3_prometheus-test.yaml

The service port 80 is defined there. This is mapped to the Prometheus 9090 port number.

Ingress rules specify a service name and its exposed port

**Pull request closed without merging**
