### PR TITLE
Add support for creating configmap directly from file

### PR DESCRIPTION
**Pull request by geekodour**
example
```
./prombench gke configmap apply -a $AUTH_FILE --name=grafana-provision --namespace=default -f dashboard.json -f datasource.json -v PROJECT_ID:$PROJECT_ID -v ZONE:$ZONE -v CLUSTER_NAME:$CLUSTER_NAME
```

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
why do we need this? Can't we use the existing deployment commands?

**Comment by geekodour** [comment]
This is an enhancement and can help with creating configmaps with contents which have conflicting syntax with go templates.

Actual format
```
"legendFormat": "{{ node }} - Cached", 
```
v/s the escaping that we're using currently:
https://github.com/prometheus/prombench/blob/ce7de2f047789896e1715826d3d8a051b786d8ec/manifests/cluster-infra/grafana_dashboard_prow_bench.yaml#L120

**Comment by geekodour** [comment]
This does not support using `DeploymentVars` though. mostly can be used for static config files.

**Comment by krasi-georgiev** [comment]
lets revisit as if we add to many ways to do same thing it will get confusing very quickly.

**Comment by geekodour** [comment]
okay, just for a reminder for later:

This will help in updating the configmap directly when the file is updated using `on:push` on `branch:master` of `prometheus/prombench` (prombench itself will use github actions for this)

secondly, it will be good but not mandatory to have these config files in a separate `configs` directory.

**Pull request closed without merging**
