### PR TITLE
Add isolation to prombench dashboard

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
I have another commit pending but github does not work
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: Internal Server Error

Commit is at https://github.com/roidelapluie/prombench/commit/4dc833a14750d34d3da4af284f1fc11c1e0cfc8a

**Comment by roidelapluie** [comment]
ok, now the commit worked ... ready for review...

iso

**Review by beorn7 — APPROVED** [review]

**Comment by geekodour** [comment]
@roidelapluie I am working on a PR to auto deploy grafana dashboards #309 , It should be completed very soon. Merging this after that will be a good idea imo.

**Comment by roidelapluie** [comment]
@geekodour I don't see the dashboard updated

**Comment by geekodour** [comment]
@roidelapluie yes, the configmap was updated and the file is updated inside the pod aswell but grafana does not seem to be picking up the changes. Weird that the change was picked up when testing the automation, sorry for the inconvenience :)  looking into it.

**Comment by geekodour** [comment]
@roidelapluie 

```
logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/prombench.json error="invalid character '{' looking for beginning of object key string"
```

Seems like will need to setup some kind of test to test changes to dashboards aswell. Making a PR to correct this change.

**Comment by krasi-georgiev** [comment]
yes maybe some CI job to spinup grafana container and just test if it will start with the new configmap

**Comment by geekodour** [comment]
@krasi-georgiev or maybe just run content of the dashboard configmap through a JSON validator? because the changes will be copied from a running grafana dashboard only. please let me know which seems like a better idea here.

**Comment by krasi-georgiev** [comment]
JSON validator would be a quick fix so lets to with that and if needed can look into other options.

**Comment by krasi-georgiev** [comment]
@roidelapluie @beorn7  btw I haven't followed the isolation PR and have no idea what this isolation_low_watermark graph represents. Not sure if grafana allows adding descriptions but maybe if you explain the idea can come up with some better name or somehow make it more obvious what is it for.

**Comment by beorn7** [comment]
I think the name is as obvious as it can be. Adding a verbose description in the tool tip (the little "i") sounds like a good idea, though.

**Pull request merged**
