### PR TITLE
[WIP]Use golang docker to build prombench

### LINKED ISSUE #145: Let's use Docker to build the binaries.
instead or relying that the local dev env has golang with modules support installed let's just use the minimal [golang docker image](https://hub.docker.com/_/golang/)

https://github.com/prometheus/prombench/blob/f13a14db5a1d3bee58999ff789cc58ff593ff22a/Makefile#L31-L33

### PR DESCRIPTION
**Pull request by sipian**
Closes #145 
Signed-off-by: Harsh Agarwal <cs15btech11019@iith.ac.in>

### CODE REVIEW

**Comment by sipian** [comment]
I am currently facing issue of not  being able to access the binary from the host.
Should merge it after this has been resolved

**Comment by geekodour** [comment]
I added a patch here: https://github.com/sipian/prombench/pull/4

**Comment by krasi-georgiev** [comment]
@geekodour would you mind opening a new PR with all changes and we can close this one so we can continue the work on your new PR.

**Comment by krasi-georgiev** [comment]
superseded in https://github.com/prometheus/prombench/pull/146

**Pull request closed without merging**
