### PR TITLE
*: bump Go version to 1.13

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by geekodour** [comment]
@simonpasquier @krasi-georgiev  won't we need a change here too? :

https://github.com/prometheus/prombench/blob/8fa36bf45520bfca6a42ba7b850750428c01a4a8/prombench/temp/prometheus-builder/Dockerfile#L1

**Comment by krasi-georgiev** [comment]
yep defensively.

**Comment by geekodour** [comment]
Just saw prometheus/prometheus is still using 1.12 so maybe not? 
https://github.com/prometheus/prometheus/blob/master/.promu.yml

**Comment by simonpasquier** [comment]
@geekodour once https://github.com/prometheus/prometheus/pull/6020 is merged, yes you would need to bump to 1.13 there too.

**Pull request merged**
