### PR TITLE
Removing unused service-account secret from 1b_secret

### PR DESCRIPTION
**Pull request by imrajdas**
Signed-off-by: Raj Babu Das <mail.rajdas@gmail.com>
- To support the PR https://github.com/prometheus/test-infra/pull/390, we need to remove this unused service-account secret from 1b_secret

- [x] Tested in GKE https://gist.github.com/rajdas98/c811dd665398bbf7ca00dabfd19267e8

### CODE REVIEW

**Comment by imrajdas** [comment]
cc @geekodour

**Comment by geekodour** [comment]
Could we also remove this?

https://github.com/prometheus/test-infra/blob/2c519dd4c7012bf84c6a2cdb590fafbd3e6771a0/prombench/Makefile#L4

**Comment by imrajdas** [comment]
AUTH_FILE is used by other make steps in Makefile. If we remove this other commands will not work

**Comment by geekodour** [comment]
We don't need the default value anymore, since we're providing it in our command runs.

It was used for this:
https://github.com/prometheus/test-infra/blob/f097e236c498833ffce85bef0042cb8041da1426/components/prow/manifests/prow_internals_2.yaml#L231

It should work, can you check?

**Comment by imrajdas** [comment]
> We don't need the default value anymore, since we're providing it in our command runs.
> 
> It was used for this:
> https://github.com/prometheus/test-infra/blob/f097e236c498833ffce85bef0042cb8041da1426/components/prow/manifests/prow_internals_2.yaml#L231
> 
> It should work, can you check?

Okay, Will remove it.

**Comment by geekodour** [comment]
could you remove this line from the readme aswell? :) as it's no longer used.
```
-v GKE_AUTH="$(cat $AUTH_FILE | base64 -w 0)" \
```

**Comment by imrajdas** [comment]
> could you remove this line from the readme aswell? :) as it's no longer used.
> 
> ```
> -v GKE_AUTH="$(cat $AUTH_FILE | base64 -w 0)" \
> ```

Removed

**Comment by geekodour** [comment]
@rajdas98 please get rid of this line aswell :) 

```
Note: Use -v GKE_AUTH="$(echo $AUTH_FILE | base64 -w 0)" if you're passing the data directly into $AUTH_FILE
```

**Pull request merged**
